### ISSUE TITLE
Calibration of 3 FSR pressure

### ISSUE THREAD

**Issue by sergiofagundes** [WingTangWong/AutoTuningFSRTrigger#6]
Is it possible to make an assisted startup calibration of the pressure applied to each the FSR's.

For example, when the firmware starts it checks the pressure at each FSR and compares with each other using a threshold to see they are all close enough, and if not blinks the led and waits for a calibration (release or tight the screws holding the bed above the FSR's) till they all get close readings ?

**Comment by WingTangWong** [comment]
Hmm... the line of thinking was that the somewhat varying analog inputs from the FSR would be converted into a digital trigger. There are pros and cons... for one thing, the non-linear response of FSR(s). Ie, linear response in the middle, but flat and exponential response at the ends.

I would not trust FSR values at startup nor during operation as consistent. There are reasons for this:

- FSR response is nonlinear and is actually divided into three distinct response regions. The datasheets for the FSR(s) you choose will indicate at what pressure ranges these regions transition.
- The FSR response degrades with length of time of contact. Ie, if you rest the FSR against the bed overnight, don't expect it to behave normally for a while. The values would be skewed until the materials comprising the point of contact have reverted to normal... if it does.
- The FSR is heat sensitive as well. Temperature variances will cause the plastic substrates to change in terms of their rigidity and hardness. This results in less force being required to create a larger value when warm/hot vs when cold.
- FSR readings will change even if a consistent force is applied. So the tolerance might be off by more than one wants/expects.

Considering that bed leveling setups are normally done with the bed heated to working temperatures, this means using the FSR to go to a position so that you can adjust the height and use the indicator as a test, can work... but just not consistently. -_-;;

For a cartesian style printer, this is probably doable provided you take care to protect the FSR from heat and continued or excessive pressure.

For a delta style printer, I would have doubts as the calibration of that platform involves more than simple height points. (tower alignment, arm length consistency, etc).

So short answer: yes, you can attempt to use the FSR values being the same to level a bed. 
But the long answer is that you would need to take precautions against the factors that would work against the reliable reading of the FSR.
